### ISSUE TITLE
Consistent solution for Color settings

### ISSUE THREAD

**Issue by cqann** [Canvim/PyPen#12]
Currently, shapes make up a major part of PyPen and its primitives, and therefore color of these shapes are a major part of PyPen. There already exists a great "Color parser" thanks to @EriKWDev, but there still needs to be an intuitive way of picking Color, StrokeColor, StrokeWidth and if Fill is needed.

## Suggested Solution
For Color and StrokeColor I am suggesting that the user is able to manipulate the default color and the default stroke color. This would mean that if a color is not specified in a primitives function (such as rectangle() ), that it would become the default color, previously set by the user. 

In the same way, if StrokeWidth is not specified in the primitive, it would default to a default_stroke_width, either set by the user or by PyPen's default values. 

Similarly, fill could be decided by a "fill" boolean that would by default be True, but the user could later change it to False.

**Comment by EriKWDev** [comment]
## Stroke Width
> For Color and StrokeColor I am suggesting that the user is able to manipulate the default color and the default stroke color. 
With something like ```settings.default_stroke_color``` ?

I agree that the user should be able to modify these. Perhaps also the ```settings.default_color``` and ```settings.default_background_color``` too. However, how do you suggest we handle if a user wants to, let's say, create one red circle with a stroke width of 2 and one blue circle with a stroke width of 5?

should we a) Specify the strokewidth on every call:
```python
settings.default_stroke_width = 2
circle(10, 10, 100, "red") # If none specified, we use the value of settings.default_stroke_width
circle(10, 10, 100, "blue", 5) # 5 is specified and hence overrides the default value
```
or b) Have some function call like:
```python
set_stroke_width(2)
circle(10, 10, 100, "red")
set_stroke_width(5)
circle(10, 10, 100, "blue")
```

I don't have much experience with how Processing does this, but how do you think we should implement it?

**Comment by EriKWDev** [comment]
I personally lean more towards something like a)

**Comment by EriKWDev** [comment]
## Fill
If we go along the lines of a), we could do fill like this:
```python
settings.fill = True
circle(10, 10, 100, "red") # Since fill is set to True, the circle will be filled
```

```python
settings.fill = False
circle(10, 10, 100, "red") # Since fill is set to False, the circle will only be drawn as an outline using either a specified line width or the default value
circle(10, 10, 100, "red", fill=True) # and it could perhaps be overwritten?
```

**Comment by cqann** [comment]
One does not exclude the other, if we went ahead and did a), if the user wanted b) that would still be possible. 

And the for the variable name, I agree that ``` settings.default_color ``` would be easy to understand, but sadly I think it would become quite tedious to write if you wanted your program to look like b). E.g Processing only only uses the short function stroke() for setting stroke color.

**Comment by cqann** [comment]
I suggest that we make the variables fill, stroke, stroke_width part of PyPen, thereby not permitting the user to use them as personal variables. These could then be connected to the settings object behind the scenes.

**Comment by cqann** [comment]
Example: 
```
fill = "#AB12AB"
stroke_width = 0
circle(200, 200, 50)
```

**Comment by EriKWDev** [comment]
I don't know.. I'm just worried that something like:

>    fill = "#AB12AB"
>    stroke_width = 0

could create more confusion than it solves. For example, we have ```settings.fps = <your preferred fps>```, and then we also have the ```FPS``` variable that gives the user the current framerate. Wouldn't the user then expect to be able to change the framerate with ```fps = 40``` too?

Same goes for ```settings.width``` and ```WIDTH```. WIDTH gives the current window width whilst settings.width sets the window's width. Should the user also be able to set it with ```width = 500```?

By exposing more and more variables, we pollute the variablespace. I would personally be able to use both a ```stroke_width``` and ```width``` variable myself without actually changing any behaviour of PyPen.

## How do we want it to work?
Secondly, how do you expect the fill variable to work?
For example, if I do:
```python
fill = "red" # or settings.fill
circle(200, 200, 50)
fill = "blue"
circle(200, 200, 50)
```
> Would I expect every circle to be red, every circle to be blue, or should every circle have the color previously specified?
> I think a lot of users would expect the last behaviour, but I don't know if we could make that work :/

EDIT: nevermind, I was thinking incorrectly xP If we make the primitives drawer always use user_sketch.fill for the color, this would obviously work :3

**Comment by EriKWDev** [comment]
## Here is an idea I had:
```python
def start():
   pass


def update(): 
   circle(200, 200, 50) # Nothing specified and nothing above, so it uses defautls from the settings object

   circle(200, 200, 50, "red") # red circle.
   circle(200, 200, 50) # also red circle since last fill-color used was red

   circle(200, 200, 50, "blue") # overrides and becomes a blue circle
   circle(200, 200, 50) # blue circle since last fill-color used was blue

   circle(200, 200, 50, "red", 5, fill=False) # outlined red circle with linewidth set to 5
   circle(200, 200, 50) # Exactly same as previous. If nothing is specified to overwrite, we use the previous settings
```

```python
def start():
   settings.fill = "blue"


def update(): 
   circle(200, 200, 50) # since fill was set to "blue" in start(), this circle will be blue

   circle(200, 200, 50, "red") # red circle.
   circle(200, 200, 50) # also red circle since last fill-color used was red
```

Simply inherit the last fill and line_width used. If one is specified, it overrides it for the next drawing.

**Comment by EriKWDev** [comment]
See https://jsfiddle.net/uk8fL5a9/
This is how koda.nu does it xP

**Comment by EriKWDev** [comment]
The system we settled on can be found in the implementation in #14, but to summarize it basically works as described in my previous comment.
All of these are supported:

```python
def start():
   pass


def update():
   circle(200, 200, 50, "blue") # Blue circle
   circle(200, 200, 50) # also blue

   # Everytime you draw something with a set fill_color, stroke_color or stroke_width
   # it overrides the options in the settings object so that the next shapes will use the
   # same settigns.

   circle(200, 200, 50, "red") # red circle.
   circle(200, 200, 50) # red circle too.
```
The following way works, but is not recommended. * You could also do:
```python
def update():
   settings.fill_color = "red"
   circle(200, 200, 50)  # red
   circle(200, 200, 50) # red

   settings.fill_color = "blue"

   circle(200, 200, 50, "red") # red circle. This overrides the settings.fill_color
   circle(200, 200, 50) # red circle too.
```

---

*: _The reason it's not recommended is that you have to keep track of what you set at what point.
For example:_
```python
def update():
   settings.fill_color = "red"
   circle(200, 200, 50) 
   circle(200, 200, 50) 
   settings.stroke_width = 5
```
_Here, the first frame will draw two red circles without stroke, but since the stroke_width is set at the very end, the following frames will all have a stroke width of 5._
